package agenttypes

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"
)

// AttackPlan is the structured output from the plan agent checkpoint (phase 2).
// The agent analyzes discovery results and produces a scanning strategy.
type AttackPlan struct {
	ModuleTags []string          `json:"module_tags,omitempty"`
	ModuleIDs  []string          `json:"module_ids,omitempty"`
	FocusAreas []string          `json:"focus_areas,omitempty"`
	SkipPaths  []string          `json:"skip_paths,omitempty"`
	Endpoints  []PlannedEndpoint `json:"endpoints,omitempty"`
	Notes      string            `json:"notes,omitempty"`
}

// PlannedEndpoint represents a prioritized endpoint in the attack plan.
type PlannedEndpoint struct {
	URL       string   `json:"url"`
	Method    string   `json:"method,omitempty"`
	Priority  string   `json:"priority"` // high, medium, low
	Rationale string   `json:"rationale,omitempty"`
	Tags      []string `json:"tags,omitempty"`
}

// TriageResult is the structured output from the triage agent checkpoint (phase 4).
// The agent reviews findings and decides whether additional scanning is needed.
type TriageResult struct {
	Confirmed      []TriagedFinding `json:"confirmed"`
	FalsePositives []TriagedFinding `json:"false_positives"`
	FollowUps      []FollowUpScan   `json:"follow_up_scans,omitempty"`
	Verdict        string           `json:"verdict"` // "done" or "rescan"
	Notes          string           `json:"notes,omitempty"`
}

// TriagedFinding is a finding that has been reviewed by the triage agent.
// FindingHash is the database finding_hash echoed back by the agent so the
// triage verdict can be written back to Finding.Status.
type TriagedFinding struct {
	Title       string `json:"title"`
	ModuleID    string `json:"module_id,omitempty"`
	URL         string `json:"url,omitempty"`
	FindingHash string `json:"finding_hash,omitempty"`
	Reason      string `json:"reason,omitempty"`
}

// TriageConfirmResult is the structured output from the single-finding
// confirmation triage agent (the `vigolium agent triage` CLI subcommand).
// The agent reasons about one finding's evidence, optionally re-probes the
// target, and returns a verdict plus reasoning.
type TriageConfirmResult struct {
	Verdict   string `json:"verdict"`   // one of TriageVerdictConfirmed, TriageVerdictFalsePositive
	Reasoning string `json:"reasoning"` // free-form explanation of how the verdict was reached
	Notes     string `json:"notes,omitempty"`
}

// Triage confirm verdict constants. The parser normalises common aliases
// ("fp", "true-positive", etc.) to these canonical values.
const (
	TriageVerdictConfirmed     = "confirmed"
	TriageVerdictFalsePositive = "false_positive"
)

// TriageConfirmTemplateID is the prompt template the triage CLI loads.
// TriageConfirmOutputSchema is the schema string in that template's frontmatter.
const (
	TriageConfirmTemplateID   = "agent-triage-confirm"
	TriageConfirmOutputSchema = "triage_confirm"
)

// FollowUpScan describes a targeted rescan recommended by the triage agent.
type FollowUpScan struct {
	URL        string   `json:"url"`
	Method     string   `json:"method,omitempty"`
	ModuleTags []string `json:"module_tags,omitempty"`
	ModuleIDs  []string `json:"module_ids,omitempty"`
	Rationale  string   `json:"rationale,omitempty"`
	TargetURLs []string `json:"target_urls,omitempty"` // specific URLs to rescan (preserves URL-to-module mapping)
}

// SourceAnalysisResult is the structured output from the source analysis phase (phase 0).
// The agent explores source code and extracts routes, session config, and custom extensions.
type SourceAnalysisResult struct {
	HTTPRecords   []AgentHTTPRecord    `json:"http_records"`
	SessionConfig *AgentSessionConfig  `json:"session_config,omitempty"`
	Extensions    []GeneratedExtension `json:"extensions,omitempty"`
	// SessionExploreNotes carries the raw explore-phase notes about auth/credentials/sessions.
	// Not serialized — used internally to provide context for session config repair.
	SessionExploreNotes string `json:"-"`
}

// AgentSessionConfig holds session definitions generated by the source analysis agent.
type AgentSessionConfig struct {
	Sessions []AgentSessionEntry `json:"sessions"`
}

// AgentSessionEntry represents a single session identity for authenticated scanning.
type AgentSessionEntry struct {
	Name    string            `json:"name"`
	Role    string            `json:"role"`              // "primary" or "compare"
	Headers map[string]string `json:"headers,omitempty"` // static auth headers
	Login   *AgentLoginFlow   `json:"login,omitempty"`   // login-based auth
}

// AgentLoginFlow defines a login flow discovered from source code analysis.
type AgentLoginFlow struct {
	URL         string             `json:"url"`
	Method      string             `json:"method"`
	ContentType string             `json:"content_type,omitempty"`
	Body        string             `json:"body,omitempty"`
	Extract     []AgentExtractRule `json:"extract,omitempty"`
	// Shorthand: type + token_path expand into extract rules.
	Type      string `json:"type,omitempty"`       // "bearer" or "cookie"
	TokenPath string `json:"token_path,omitempty"` // JSONPath for bearer type
	// Response validation.
	Expect *AgentExpectResponse `json:"expect,omitempty"`
}

// AgentExpectResponse defines expected response constraints for validation.
type AgentExpectResponse struct {
	Status       []int  `json:"status,omitempty"`
	BodyContains string `json:"body_contains,omitempty"`
}

// UnmarshalJSON implements lenient parsing for AgentExpectResponse.
// Handles: status as ["200","201"], status as single int/string, body_contains as any type.
func (r *AgentExpectResponse) UnmarshalJSON(data []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if v, ok := raw["status"]; ok {
		r.Status = flexIntSlice(v)
	}
	if v, ok := raw["body_contains"]; ok {
		r.BodyContains = fmt.Sprint(v)
	}
	return nil
}

// AgentExtractRule defines how to extract an auth token from a login response.
type AgentExtractRule struct {
	Source  string `json:"source"`             // "cookie", "json", "header", "regex"
	Name    string `json:"name,omitempty"`     // cookie name or header name
	Path    string `json:"path,omitempty"`     // JSONPath for json source
	ApplyAs string `json:"apply_as,omitempty"` // e.g. "Authorization: Bearer {value}"
	Pattern string `json:"pattern,omitempty"`  // regex pattern (source: "regex")
	Group   int    `json:"group,omitempty"`    // capture group index (source: "regex")
}

// UnmarshalJSON implements lenient parsing for AgentExtractRule.
// Handles: group as string "1", all string fields as any type.
func (r *AgentExtractRule) UnmarshalJSON(data []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if v, ok := raw["source"]; ok {
		r.Source = fmt.Sprint(v)
	}
	if v, ok := raw["name"]; ok {
		r.Name = fmt.Sprint(v)
	}
	if v, ok := raw["path"]; ok {
		r.Path = fmt.Sprint(v)
	}
	if v, ok := raw["apply_as"]; ok {
		r.ApplyAs = fmt.Sprint(v)
	}
	if v, ok := raw["pattern"]; ok {
		r.Pattern = fmt.Sprint(v)
	}
	if v, ok := raw["group"]; ok {
		r.Group = flexInt(v)
	}
	return nil
}

// GeneratedExtension represents a JavaScript extension generated by the agent.
type GeneratedExtension struct {
	Filename string `json:"filename"`
	Code     string `json:"code"`
	Reason   string `json:"reason"`
}

// QuickCheck is a declarative shorthand for simple payload-and-match scan checks.
// The swarm runner auto-generates a full JS extension from each QuickCheck.
type QuickCheck struct {
	ID       string              `json:"id"`
	Severity string              `json:"severity,omitempty"` // default: "medium"
	Scan     string              `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Payloads []string            `json:"payloads,omitempty"` // for per_insertion_point: payloads to inject
	Requests []QuickCheckRequest `json:"requests,omitempty"` // for per_request/per_host: requests to send
	Match    QuickCheckMatch     `json:"match"`
}

// QuickCheckRequest defines a request to send in per_request/per_host quick checks.
type QuickCheckRequest struct {
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
}

// QuickCheckMatch defines match conditions for a quick check (OR logic).
type QuickCheckMatch struct {
	BodyContains   string `json:"body_contains,omitempty"`
	BodyRegex      string `json:"body_regex,omitempty"`
	Status         int    `json:"status,omitempty"`
	HeaderContains string `json:"header_contains,omitempty"`
}

// UnmarshalJSON implements lenient parsing for QuickCheckMatch.
// Handles: status as string "200".
func (m *QuickCheckMatch) UnmarshalJSON(data []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if v, ok := raw["body_contains"]; ok {
		m.BodyContains = fmt.Sprint(v)
	}
	if v, ok := raw["body_regex"]; ok {
		m.BodyRegex = fmt.Sprint(v)
	}
	if v, ok := raw["status"]; ok {
		m.Status = flexInt(v)
	}
	if v, ok := raw["header_contains"]; ok {
		m.HeaderContains = fmt.Sprint(v)
	}
	return nil
}

// Snippet is a shorthand extension where only the scan function body is provided.
// The swarm runner wraps it in a full module scaffold with access to ctx, insertion, and vigolium.* APIs.
type Snippet struct {
	ID       string `json:"id"`
	Severity string `json:"severity,omitempty"` // default: "medium"
	Scan     string `json:"scan"`               // "per_insertion_point", "per_request", "per_host"
	Body     string `json:"body"`               // JS function body
}

// SwarmPlan is the structured output from the master agent in agent swarm mode.
// The agent analyzes the target request, selects modules, and generates custom extensions.
type SwarmPlan struct {
	ModuleTags  []string             `json:"module_tags,omitempty"`
	ModuleIDs   []string             `json:"module_ids,omitempty"`
	Extensions  []GeneratedExtension `json:"extensions,omitempty"`
	QuickChecks []QuickCheck         `json:"quick_checks,omitempty"`
	Snippets    []Snippet            `json:"snippets,omitempty"`
	FocusAreas  []string             `json:"focus_areas,omitempty"`
	// RecommendedSkills is the planner's context-driven selection of skill
	// names (from the <available_skills> menu) that the triage phase should
	// load for confirmation/escalation. Unioned with the always-on set and any
	// operator override before the triage engine is built.
	RecommendedSkills     []string `json:"recommended_skills,omitempty"`
	Notes                 string   `json:"notes,omitempty"`
	NeedsExtensions       bool     `json:"needs_extensions,omitempty"`
	NeedsExtensionsReason string   `json:"needs_extensions_reason,omitempty"`
	ExtensionAgentError   string   `json:"extension_agent_error,omitempty"`
}

// BatchProvenance tracks which batch contributed each item to a merged plan.
type BatchProvenance struct {
	ModuleTags map[string]int `json:"module_tags,omitempty"` // tag -> batch number
	ModuleIDs  map[string]int `json:"module_ids,omitempty"`  // id -> batch number
	Extensions map[string]int `json:"extensions,omitempty"`  // filename -> batch number
	FocusAreas map[string]int `json:"focus_areas,omitempty"` // focus area -> batch number
}

// TokenUsage tracks cumulative token consumption across agent calls in a run.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// ProgressEvent reports granular progress during agent scans.
type ProgressEvent struct {
	Phase        string `json:"phase"`
	SubPhase     string `json:"sub_phase,omitempty"`
	Current      int    `json:"current,omitempty"`
	Total        int    `json:"total,omitempty"`
	FindingCount int    `json:"finding_count,omitempty"`
	Message      string `json:"message,omitempty"`
}

// SwarmResult holds the outcome of an agent swarm run.
type SwarmResult struct {
	SwarmPlan       *SwarmPlan               `json:"swarm_plan,omitempty"`
	TriageResults   []*TriageResult          `json:"triage_results,omitempty"`
	TotalFindings   int                      `json:"total_findings"`
	TotalRecords    int                      `json:"total_records"`
	SeverityCounts  map[string]int           `json:"severity_counts,omitempty"` // critical, high, medium, low, info
	Confirmed       int                      `json:"confirmed"`
	FalsePositives  int                      `json:"false_positives"`
	Iterations      int                      `json:"iterations"`
	Duration        time.Duration            `json:"duration"`
	AgenticScanUUID string                   `json:"agentic_scan_uuid"`
	SessionDir      string                   `json:"session_dir,omitempty"`
	PhaseTimings    map[string]time.Duration `json:"phase_timings,omitempty"`
	TokenUsage      TokenUsage               `json:"token_usage,omitempty"`
	BatchProvenance *BatchProvenance         `json:"batch_provenance,omitempty"` // only set when plan was merged from multiple batches
	Degraded        bool                     `json:"degraded,omitempty"`
	Warnings        []string                 `json:"warnings,omitempty"`
}

// SwarmCheckpoint captures swarm pipeline state for checkpoint/resume.
type SwarmCheckpoint struct {
	CompletedPhases  []string          `json:"completed_phases"`
	TargetURL        string            `json:"target_url"`
	RecordCount      int               `json:"record_count"`
	Plan             *SwarmPlan        `json:"plan,omitempty"`
	ExtensionDir     string            `json:"extension_dir,omitempty"`
	Timestamp        time.Time         `json:"timestamp"`
	TriageRound      int               `json:"triage_round,omitempty"`      // last completed triage round (0-indexed)
	ExtensionRenames map[string]string `json:"extension_renames,omitempty"` // original filename -> renamed filename
	LastFindingID    int64             `json:"last_finding_id,omitempty"`
	Warnings         []string          `json:"warnings,omitempty"`
	InitialRecords   int               `json:"initial_records,omitempty"`
	SourceRecords    int               `json:"source_records,omitempty"`
	DiscoveryRecords int               `json:"discovery_records,omitempty"`
}

// LastPhase returns the last completed phase, or "" if none.
func (cp *SwarmCheckpoint) LastPhase() string {
	if cp == nil || len(cp.CompletedPhases) == 0 {
		return ""
	}
	return cp.CompletedPhases[len(cp.CompletedPhases)-1]
}

// ScanRequest is the configuration for a native scan callback.
type ScanRequest struct {
	ModuleTags   []string // module tags from the agent's plan
	ModuleIDs    []string // explicit module IDs from the agent's plan
	ExtensionDir string   // path to generated JS extensions (empty if none)
	IsRescan     bool     // true for triage-driven targeted rescans
	TargetURLs   []string // optional: restrict rescan to these URLs only
}

// ScanFunc is the unified callback signature for running scans.
type ScanFunc func(ctx context.Context, req ScanRequest) error

// DiffContext holds parsed diff information for focused scanning.
// When present, the agent and vigolium-audit prioritize the changed files.
type DiffContext struct {
	ChangedFiles []string `json:"changed_files"`           // changed file paths relative to source root
	PatchContent string   `json:"patch_content,omitempty"` // unified diff patch content
	DiffRef      string   `json:"diff_ref"`                // original ref/URL for display (e.g. "origin/main...feature")
}

// ResolvedSource holds the result of source path resolution.
// The --source flag may be a local path, git URL, or archive file;
// ResolveSource() normalizes all of these into a local directory path.
type ResolvedSource struct {
	LocalPath string // absolute local filesystem path to source
}

// SourceAnalysisConfig holds parameters for a source code analysis run.
type SourceAnalysisConfig struct {
	AgentName      string
	TargetURL      string
	SourcePath     string
	Files          []string
	Instruction    string // user-provided custom instruction appended to the prompt
	DryRun         bool
	ShowPrompt     bool // print rendered prompt to stderr before executing
	ScanUUID       string
	ProjectUUID    string
	StreamWriter   io.Writer
	SessionDir     string // when set, per-phase prompt/output files are written here
	MaxConcurrency int    // max parallel sub-agents in RunSourceAnalysisParallel (0 = default 3)
}

// InvalidExtension holds an extension that failed syntax validation along with
// the compile error, so it can be passed to the LLM for repair.
type InvalidExtension struct {
	Extension GeneratedExtension
	Err       error
}

// QuickCheckLintIssue represents a single lint finding for a quick check or snippet.
type QuickCheckLintIssue struct {
	Severity string // "error" or "warning"
	Message  string
}

// RepairConfig holds agent settings for the repair LLM call.
type RepairConfig struct {
	AgentName    string
	ShowPrompt   bool
	TargetURL    string   // target URL for regeneration context
	FocusAreas   []string // focus areas from the swarm plan
	ModuleTags   []string // module tags from the swarm plan
	ExploreNotes string   // session explore notes for context-aware session repair (optional)
}

// AgentExtensionsOutput wraps a list of extensions for JSON parsing.
type AgentExtensionsOutput struct {
	Extensions []GeneratedExtension `json:"extensions"`
	// These fields may appear in the same JSON block (from swarm plan output)
	QuickChecks []QuickCheck `json:"quick_checks,omitempty"`
	Snippets    []Snippet    `json:"snippets,omitempty"`
}
