package auth_headers_detect

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vigolium/vigolium/pkg/httpmsg"
	"github.com/vigolium/vigolium/pkg/modules/modkit"
)

func TestNew(t *testing.T) {
	t.Parallel()
	m := New()
	require.NotNil(t, m)
	assert.Equal(t, ModuleID, m.ID())
	assert.Equal(t, ModuleName, m.Name())
}

// makeReqCtx builds a request/response pair from raw request headers, with a
// plain 200 application response.
func makeReqCtx(path, reqHeaders string) *httpmsg.HttpRequestResponse {
	return makeReqCtxWithResp(path, reqHeaders,
		"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{}")
}

// makeReqCtxWithResp builds a request/response pair with a caller-supplied raw
// response, so tests can drive non-2xx and edge-block responses.
func makeReqCtxWithResp(path, reqHeaders, rawResp string) *httpmsg.HttpRequestResponse {
	rawReq := []byte(fmt.Sprintf("GET %s HTTP/1.1\r\nHost: example.com\r\n%s\r\n", path, reqHeaders))
	req := httpmsg.NewHttpRequestWithService(
		httpmsg.NewServiceSecure("example.com", 443, true),
		rawReq,
	)
	resp := httpmsg.NewHttpResponse([]byte(rawResp))
	return httpmsg.NewHttpRequestResponse(req, resp)
}

// TestScanPerRequest_BearerToken drives a request carrying an Authorization
// bearer token, which should be flagged.
func TestScanPerRequest_BearerToken(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := makeReqCtx("/api/profile", "Authorization: Bearer eyJhbGciOiJIUzI1Ni1.payload.sig\r\n")

	results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
	require.NoError(t, err)
	require.NotEmpty(t, results)
	assert.Equal(t, "Authorization", results[0].FuzzingParameter)
	require.NotEmpty(t, results[0].ExtractedResults)
}

// TestScanPerRequest_NoAuth verifies a request without an Authorization header
// produces no findings.
func TestScanPerRequest_NoAuth(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := makeReqCtx("/api/public", "")

	results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, results)
}

// TestScanPerRequest_MediaSkipped verifies that media URLs are skipped even when
// they carry an Authorization header.
func TestScanPerRequest_MediaSkipped(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := makeReqCtx("/logo.png", "Authorization: Bearer token123\r\n")

	results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, results)
}

// TestScanPerRequest_NoCredentialMaterial verifies that an Authorization header
// carrying no actual credential — a bare scheme or a JS placeholder — is not
// flagged. This is the motivating false positive ("Authorization: Bearer").
func TestScanPerRequest_NoCredentialMaterial(t *testing.T) {
	t.Parallel()
	for _, hv := range []string{
		"Bearer",      // bare scheme, no token (the reported FP)
		"Bearer ",     // bare scheme with trailing space
		"Bearer null", // JS placeholder
		"Bearer undefined",
		"Basic",
		"null",
	} {
		m := New()
		ctx := makeReqCtx("/api/profile", "Authorization: "+hv+"\r\n")
		results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
		require.NoError(t, err)
		assert.Emptyf(t, results, "header %q should not be flagged", hv)
	}
}

// TestScanPerRequest_EdgeBlocked verifies that a real credential whose response
// is a WAF/CDN edge block (CloudFront "Request blocked" 403) is not flagged: the
// request never reached an authenticated boundary.
func TestScanPerRequest_EdgeBlocked(t *testing.T) {
	t.Parallel()
	m := New()
	rawResp := "HTTP/1.1 403 Forbidden\r\nServer: CloudFront\r\nContent-Type: text/html\r\n\r\n" +
		"<H1>403 ERROR</H1>Request blocked.\nGenerated by cloudfront (CloudFront)"
	ctx := makeReqCtxWithResp("/api/profile",
		"Authorization: Bearer eyJhbGciOiJIUzI1Ni1.payload.sig\r\n", rawResp)

	results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
	require.NoError(t, err)
	assert.Empty(t, results)
}

// TestScanPerRequest_AppForbiddenKept verifies that a genuine application 403
// (not an edge block) with a real token is still flagged — it marks a protected
// endpoint and captures a sensitive credential, which is the module's purpose.
func TestScanPerRequest_AppForbiddenKept(t *testing.T) {
	t.Parallel()
	m := New()
	rawResp := "HTTP/1.1 403 Forbidden\r\nServer: nginx\r\nContent-Type: application/json\r\n\r\n" +
		`{"error":"insufficient_scope"}`
	ctx := makeReqCtxWithResp("/api/profile",
		"Authorization: Bearer eyJhbGciOiJIUzI1Ni1.payload.sig\r\n", rawResp)

	results, err := m.ScanPerRequest(ctx, &modkit.ScanContext{})
	require.NoError(t, err)
	require.NotEmpty(t, results)
}
