package modkit

import (
	"strings"

	"github.com/vigolium/vigolium/pkg/httpmsg"
	"github.com/vigolium/vigolium/pkg/modules/infra"
)

// edgeBlockBodyScanLimit caps how many leading body bytes are scanned for edge
// block / challenge markers. Interstitial pages carry their markers in the first
// few KB; the cap keeps the check cheap on large application responses.
const edgeBlockBodyScanLimit = 16 << 10

// edgeBlockBodyMarkers are byte needles that appear only on a WAF/CDN edge block
// or interstitial challenge page, never in a genuine application response. It is
// the shared Cloudflare/Incapsula challenge set (infra.ChallengeBodyMarkers) plus
// the CloudFront error-page markers specific to edge blocks — so a new challenge
// string added to the shared set is picked up here automatically.
var edgeBlockBodyMarkers = append([][]byte{
	[]byte("Generated by cloudfront"),            // CloudFront error page footer
	[]byte("The request could not be satisfied"), // CloudFront error page title
}, infra.ChallengeBodyMarkers...)

// edgeBlockBodyMatcher is the single-pass form of edgeBlockBodyMarkers, built
// once so IsEdgeBlockedResponse scans the (capped) body a single time instead of
// once per marker.
var edgeBlockBodyMatcher = infra.NewByteSetMatcher(edgeBlockBodyMarkers)

// IsEdgeBlockedResponse reports whether resp came from a WAF/CDN edge block or
// interstitial challenge rather than the application. It is the passive-module
// counterpart to infra.IsBlockedResponse, which requires a *httputil.ResponseChain
// that passive modules do not hold: this works against the raw httpmsg response
// (status + Server/X-CDN/Cf-Mitigated headers + body markers).
//
// A content/value-leak detector that flags a secret, token, version string,
// stack trace, or sensitive field by matching the RESPONSE body or headers MUST
// skip such a response: a denied/challenged page is the edge talking, not the
// application, so any token it carries can only be a false positive (the
// motivating case: an "Authorization" finding on a CloudFront "Request blocked"
// 403, and the broader Cloudflare-challenge-token-as-SQLi class).
//
// It deliberately recognizes only vendor-identified edge blocks (Server/CDN
// headers, challenge markers, 429). It does NOT treat a generic application
// 401/403 as a block, so a module whose finding legitimately rides a protected
// or app-rendered error response keeps it. Do NOT use it in a module whose
// finding IS a blocking status (an access-control 403 check) — it would suppress
// the very response that module looks for.
func IsEdgeBlockedResponse(resp *httpmsg.HttpResponse) bool {
	if resp == nil {
		return false
	}
	// Status-independent challenge: Cloudflare stamps this on any response it
	// challenged or blocked, including ones returned with a 200/202.
	if resp.Header("Cf-Mitigated") != "" {
		return true
	}
	server := strings.ToLower(strings.TrimSpace(resp.Header("Server")))
	switch resp.StatusCode() {
	case 429:
		return true
	case 403, 503:
		switch {
		case strings.HasPrefix(server, "cloudflare"),
			strings.HasPrefix(server, "akamaighost"),
			server == "cloudfront",
			strings.HasPrefix(server, "awselb/"):
			return true
		}
		if strings.EqualFold(resp.Header("X-CDN"), "Incapsula") {
			return true
		}
	}
	body := resp.Body()
	if len(body) > edgeBlockBodyScanLimit {
		body = body[:edgeBlockBodyScanLimit]
	}
	return edgeBlockBodyMatcher.MatchAny(body)
}
