package modkit

import (
	"testing"

	"github.com/vigolium/vigolium/pkg/httpmsg"
)

func respFromRaw(raw string) *httpmsg.HttpResponse {
	return httpmsg.NewHttpResponse([]byte(raw))
}

func TestIsEdgeBlockedResponse(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		raw  string
		want bool
	}{
		{
			name: "cloudfront request blocked 403",
			raw:  "HTTP/1.1 403 Forbidden\r\nServer: CloudFront\r\nContent-Type: text/html\r\n\r\n<H1>403 ERROR</H1>The request could not be satisfied.\nGenerated by cloudfront (CloudFront)",
			want: true,
		},
		{
			name: "cloudflare challenge 403 by server header",
			raw:  "HTTP/1.1 403 Forbidden\r\nServer: cloudflare\r\n\r\nattention required",
			want: true,
		},
		{
			name: "cloudflare challenge 200 by cf-mitigated",
			raw:  "HTTP/1.1 200 OK\r\nServer: cloudflare\r\nCf-Mitigated: challenge\r\n\r\n<html></html>",
			want: true,
		},
		{
			name: "cloudflare js challenge by body marker",
			raw:  "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<html><head></head><body>window._cf_chl_opt={}</body></html>",
			want: true,
		},
		{
			name: "akamai 403",
			raw:  "HTTP/1.1 403 Forbidden\r\nServer: AkamaiGHost\r\n\r\nAccess Denied",
			want: true,
		},
		{
			name: "rate limited 429",
			raw:  "HTTP/1.1 429 Too Many Requests\r\nServer: nginx\r\n\r\nslow down",
			want: true,
		},
		{
			name: "genuine app 403 (nginx) is not an edge block",
			raw:  "HTTP/1.1 403 Forbidden\r\nServer: nginx\r\nContent-Type: application/json\r\n\r\n{\"error\":\"insufficient_scope\"}",
			want: false,
		},
		{
			name: "genuine app 401 is not an edge block",
			raw:  "HTTP/1.1 401 Unauthorized\r\nServer: nginx\r\n\r\n{\"error\":\"unauthorized\"}",
			want: false,
		},
		{
			name: "normal 200 app response",
			raw:  "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"ok\":true}",
			want: false,
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := IsEdgeBlockedResponse(respFromRaw(tc.raw)); got != tc.want {
				t.Fatalf("IsEdgeBlockedResponse() = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestIsEdgeBlockedResponse_Nil(t *testing.T) {
	t.Parallel()
	if IsEdgeBlockedResponse(nil) {
		t.Fatal("nil response must not be treated as blocked")
	}
}

func TestIsPlaceholderValue(t *testing.T) {
	t.Parallel()
	placeholders := []string{"", "  ", "null", "NULL", "undefined", "nil", "none", "NaN", "(null)", "[object Object]", "{}", "[]"}
	for _, v := range placeholders {
		if !IsPlaceholderValue(v) {
			t.Errorf("IsPlaceholderValue(%q) = false, want true", v)
		}
	}
	real := []string{"abc123", "0", "true", "false", "eyJhbGci.payload.sig", "https://example.com", "42"}
	for _, v := range real {
		if IsPlaceholderValue(v) {
			t.Errorf("IsPlaceholderValue(%q) = true, want false", v)
		}
	}
}
