package http_request_smuggling

import (
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vigolium/vigolium/pkg/httpmsg"
	"github.com/vigolium/vigolium/pkg/modules/modkit"
	"github.com/vigolium/vigolium/pkg/types/severity"
)

func TestNew(t *testing.T) {
	m := New()
	assert.Equal(t, ModuleID, m.ID())
	assert.Equal(t, ModuleName, m.Name())
	assert.Equal(t, severity.Suspect, m.Severity())
	assert.Equal(t, severity.Tentative, m.Confidence())
	assert.Equal(t, modkit.ScanScopeHost, m.ScanScopes())
}

func TestCanProcess(t *testing.T) {
	m := New()

	t.Run("nil context", func(t *testing.T) {
		assert.False(t, m.CanProcess(nil))
	})

	t.Run("no request", func(t *testing.T) {
		ctx := httpmsg.NewHttpRequestResponse(nil, nil)
		assert.False(t, m.CanProcess(ctx))
	})

	t.Run("request without response", func(t *testing.T) {
		ctx, err := httpmsg.ParseRawRequest("GET / HTTP/1.1\r\nHost: example.com\r\n\r\n")
		require.NoError(t, err)
		assert.False(t, m.CanProcess(ctx), "smuggling needs a baseline response to compare timing against")
	})

	t.Run("request with response", func(t *testing.T) {
		ctx, err := httpmsg.ParseRawRequest("GET / HTTP/1.1\r\nHost: example.com\r\n\r\n")
		require.NoError(t, err)
		resp := httpmsg.NewHttpResponse([]byte("HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"))
		ctxWithResp := httpmsg.NewHttpRequestResponse(ctx.Request(), resp)
		assert.True(t, m.CanProcess(ctxWithResp))
	})
}

// TestProbesWellFormed verifies every desync probe carries the conflicting
// Content-Length / Transfer-Encoding headers that make it a smuggling probe.
// A probe that lost one of these headers (e.g. via a refactor) would silently
// stop testing for desync while still appearing in the probe list.
func TestProbesWellFormed(t *testing.T) {
	assert.NotEmpty(t, probes, "probe table must not be empty")

	names := map[string]struct{}{}
	for i, p := range probes {
		assert.NotEmpty(t, p.name, "probe[%d] must have a name", i)
		assert.NotEmpty(t, p.desc, "probe[%d] (%s) must have a description", i, p.name)
		assert.NotEmpty(t, p.body, "probe[%d] (%s) must have a body", i, p.name)

		_, hasCL := p.headers["Content-Length"]
		_, hasTE := p.headers["Transfer-Encoding"]
		assert.True(t, hasCL, "probe[%d] (%s) must set Content-Length to create a desync", i, p.name)
		assert.True(t, hasTE, "probe[%d] (%s) must set Transfer-Encoding to create a desync", i, p.name)

		if _, dup := names[p.name]; dup {
			t.Errorf("duplicate probe name %q", p.name)
		}
		names[p.name] = struct{}{}
	}
}

// cloudflareEdgeRestrictedBody is the body Cloudflare served for the real
// false-positive report: a 403 "Edge IP Restricted" (error 1034) page. The
// request was rejected at the edge and never reached an origin frontend/backend
// chain, so the 7.3s vs 1.4s timing gap was edge processing, not a desync.
const cloudflareEdgeRestrictedBody = `<!doctype html>
<html class="no-js" lang="en-US">
  <head><title>Edge IP Restricted | example.com | Cloudflare</title></head>
  <body>
    <div id="cf-error-details" class="p-0">
      <h1><span>Error</span> <span>1034</span></h1>
      <h2 class="text-gray-600">Edge IP Restricted</h2>
      <link rel="stylesheet" href="/cdn-cgi/styles/main.css" />
      <span>Cloudflare Ray ID: <strong>a05680a3b81891cc</strong></span>
    </div>
  </body>
</html>`

// TestLooksLikeEdgeBlockPage covers the body-marker block detection that backs
// the smuggling false-positive fix.
func TestLooksLikeEdgeBlockPage(t *testing.T) {
	t.Run("cloudflare edge ip restricted (the reported FP)", func(t *testing.T) {
		assert.True(t, looksLikeEdgeBlockPage(cloudflareEdgeRestrictedBody),
			"Cloudflare 403 edge block page must be recognized so it never backs a finding")
	})

	t.Run("various edge/WAF markers", func(t *testing.T) {
		blocks := []string{
			`<div id="cf-error-details">Attention Required! | Cloudflare</div>`,
			`Access Denied - server: AkamaiGHost`,
			`Request unsuccessful. Incapsula incident ID: 123`,
			`The request could not be satisfied. Generated by cloudfront`,
			`<html>error 1020 access denied</html>`,
		}
		for _, b := range blocks {
			assert.True(t, looksLikeEdgeBlockPage(b), "should flag block page: %q", b)
		}
	})

	t.Run("legitimate origin response is not a block", func(t *testing.T) {
		assert.False(t, looksLikeEdgeBlockPage(""))
		assert.False(t, looksLikeEdgeBlockPage(`<html><body>Welcome to the app dashboard</body></html>`))
		assert.False(t, looksLikeEdgeBlockPage(`{"status":"ok","data":[]}`))
	})
}

// TestIsTimingAnomaly verifies the dual relative+absolute gate. The reported FP
// (baseline 1.367s, probe 7.306s) clears the gate, which is exactly why timing
// alone is insufficient and the block/control confirmation is required.
func TestIsTimingAnomaly(t *testing.T) {
	baseline := 1367 * time.Millisecond

	assert.True(t, isTimingAnomaly(7306*time.Millisecond, baseline),
		"reported FP timing clears the raw anomaly gate (hence the need for confirmation)")

	// Absolute floor: 5x a tiny baseline is still well under the 5s floor.
	assert.False(t, isTimingAnomaly(900*time.Millisecond, 100*time.Millisecond),
		"must clear the absolute 5s floor, not just the relative multiplier")

	// Relative gate: slow in absolute terms but not 5x the (already slow) baseline.
	assert.False(t, isTimingAnomaly(6*time.Second, 4*time.Second),
		"must be >5x the baseline, not just over the floor")

	assert.False(t, isTimingAnomaly(baseline, baseline))
}

// TestBuildProbeRequest verifies a probe is forced to POST and carries its
// conflicting CL/TE framing.
func TestBuildProbeRequest(t *testing.T) {
	ctx, err := httpmsg.ParseRawRequest("GET / HTTP/1.1\r\nHost: example.com\r\n\r\n")
	require.NoError(t, err)

	raw, ok := buildProbeRequest(ctx, probes[1]) // TE.CL Basic
	require.True(t, ok)

	out := string(raw)
	assert.True(t, strings.HasPrefix(out, "POST "), "probe must be forced to POST")
	lower := strings.ToLower(out)
	assert.Contains(t, lower, "transfer-encoding:", "probe must keep its Transfer-Encoding header")
	assert.Contains(t, lower, "content-length:", "probe must keep its Content-Length header")
}

// TestBuildControlRequest verifies the control is an unambiguous, well-formed
// POST: no Transfer-Encoding and a Content-Length that matches its body, so it
// can never trigger a CL/TE desync.
func TestBuildControlRequest(t *testing.T) {
	ctx, err := httpmsg.ParseRawRequest(
		"GET / HTTP/1.1\r\nHost: example.com\r\nTransfer-Encoding: chunked\r\n\r\n")
	require.NoError(t, err)

	raw, ok := buildControlRequest(ctx)
	require.True(t, ok)

	out := string(raw)
	assert.True(t, strings.HasPrefix(out, "POST "), "control must be a POST")
	assert.NotContains(t, strings.ToLower(out), "transfer-encoding:",
		"control must drop Transfer-Encoding to avoid any framing ambiguity")
	assert.Contains(t, strings.ToLower(out), "content-length: 1",
		"control body length must match its Content-Length")
	assert.True(t, strings.HasSuffix(out, "1"), "control must carry the well-formed body")
}
